# This is a basic workflow to help you get started with Actions

name: CI

env: 
  DATABASE: ${{secrets.DATABASE}}
  DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  pull_request_review:
    types: [submitted]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: hello world
        run: echo hello world
      - name: ENV variables
        run: echo ${DATABASE}
      # Runs a set of commands using the runners shell
      - name: install dependencies
        run: npm install
        
      - name: Run Test suite
        run: npm test
